id: P004631
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:45:30.649060
source_metadata:
  id: bdr:W21727
  title: རིག་འཛིན་པདམ་གླིང་པའི་ཟབ་གཏེར་ཆོས་མཛོད་རིན་པོ་ཆེ།
  author: ''
  volumes:
    43370d528ccb401384809b207318d703:
      image_group_id: I1905
      title: ''
      volume_number: 1
      total_pages: 905
      base_file: v001.txt
    75af6d18fbe64f1c81ca11f28054b8d7:
      image_group_id: I1906
      title: ''
      volume_number: 2
      total_pages: 966
      base_file: v002.txt
    29bd30baa9364d2ab036c041244a5462:
      image_group_id: I1907
      title: ''
      volume_number: 3
      total_pages: 773
      base_file: v003.txt
    a865acda4f754d36ac2b9c8f6e7c8478:
      image_group_id: I1908
      title: ''
      volume_number: 4
      total_pages: 483
      base_file: v004.txt
    fe8195640f0b4922beec4945e73f10ba:
      image_group_id: I1909
      title: ''
      volume_number: 5
      total_pages: 537
      base_file: v005.txt
    1774b3a86fd6441d8fbba10165b0d169:
      image_group_id: I1910
      title: ''
      volume_number: 6
      total_pages: 745
      base_file: v006.txt
    5a5c633272b5424c9556a08afdd3a411:
      image_group_id: I1911
      title: ''
      volume_number: 7
      total_pages: 591
      base_file: v007.txt
    a24c28ddd8684992be675108230533e7:
      image_group_id: I1912
      title: ''
      volume_number: 8
      total_pages: 347
      base_file: v008.txt
    1bf85e4963fe40bfa81df7c7f5e88119:
      image_group_id: I1913
      title: ''
      volume_number: 9
      total_pages: 545
      base_file: v009.txt
    9dd2a1a915cd4373b3b3069f390b68af:
      image_group_id: I1914
      title: ''
      volume_number: 10
      total_pages: 689
      base_file: v010.txt
    9ad7b40b8e6e43759b6e7c2a17d21ecf:
      image_group_id: I1915
      title: ''
      volume_number: 11
      total_pages: 633
      base_file: v011.txt
    61727a5a0b4a491da1382cbf3f4c9d9a:
      image_group_id: I1916
      title: ''
      volume_number: 12
      total_pages: 315
      base_file: v012.txt
    cfd896938cd640539aae6408bdbf1b98:
      image_group_id: I1917
      title: ''
      volume_number: 13
      total_pages: 629
      base_file: v013.txt
    00152f5bf7204a0596ab06b2a1c91306:
      image_group_id: I1918
      title: ''
      volume_number: 14
      total_pages: 635
      base_file: v014.txt
    3ccef20a50404a14b34dc70139248ea2:
      image_group_id: I1919
      title: ''
      volume_number: 15
      total_pages: 673
      base_file: v015.txt
    074a0040890f4a4aa375389764cfb296:
      image_group_id: I1920
      title: ''
      volume_number: 16
      total_pages: 389
      base_file: v016.txt
    d65ec87ed87d43c1bc42059a36b6fdd2:
      image_group_id: I1921
      title: ''
      volume_number: 17
      total_pages: 527
      base_file: v017.txt
    1aca02ec50b24a01b4572dee4daf4698:
      image_group_id: I1922
      title: ''
      volume_number: 18
      total_pages: 629
      base_file: v018.txt
    8980397ad9074bc1875bf16d0b23cddd:
      image_group_id: I1923
      title: ''
      volume_number: 19
      total_pages: 945
      base_file: v019.txt
    088d1f6b1f3a437ca5842da15ce3a305:
      image_group_id: I1924
      title: ''
      volume_number: 20
      total_pages: 199
      base_file: v020.txt
    4a664236b09d41d389eae54936802df6:
      image_group_id: I1925
      title: ''
      volume_number: 21
      total_pages: 915
      base_file: v021.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
